site_name: CSC3034 CI Labs
theme:
  name: material
  custom_dir: "custom"
  favicon: img/favicon.ico
  logo: img/favicon.ico
  palette:
    primary: white
  features:
    - toc.integrate
nav:
  - Home: index.md
  - Lab 1: lab1.md
markdown_extensions:
  - meta
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
