site_name: CSC3034 CI Labs
site_url: https://ricwtk.github.io/ci-labs
docs_dir: src
site_dir: docs
theme:
  name: material
  custom_dir: "custom"
  favicon: img/favicon.ico
  logo: img/favicon.ico
  palette:
    scheme: default
    primary: teal
    accent: teal
  features:
    - toc.integrate
    - navigation.tabs
nav:
  - Current:
    - Overview: index.md
    - lab1.md
    - lab2.md
    - lab3.md
    - lab4.md
    - lab5.md
    - lab6.md
    - lab7.md
  - Archive:
    - 201908:
      - archive/201908/lab1.md
      - archive/201908/lab2.md
      - archive/201908/lab3.md
      - archive/201908/lab4.md
      - archive/201908/lab5.md
      - archive/201908/lab6.md
      - archive/201908/lab7.md
    - 202008:
      - archive/202008/lab1.md
      - archive/202008/lab2.md
      - archive/202008/lab3.md
      - archive/202008/lab4.md
      - archive/202008/lab5.md
      - archive/202008/lab6.md
      - archive/202008/lab7.md
markdown_extensions:
  - meta
  - pymdownx.tabbed
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
